<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voting system</title>
    <!-- <link rel="stylesheet" href="css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>

    </style>

</head>
<body>
        <div class="container">
            <div class="col-sm-6">
            <?php
                       include('../database_connection.php');
                       $id=$_GET['id'];
                       $select="SELECT * from idrequest where id='$id'";
                       $result=$conn->query(($select));
                       if($result->num_rows>0) 
                       {
                           $suffix="";
                           $prefix="";
                           $id_generated="";
                           while($row=$result->fetch_array())
                           {
                                $user_email=$row['userEmail'];
                                $user_RollNo=$row['rollNo'];
                                $branch=$row['branch'];
                           }
                           switch($branch)
                           {
                                case "IT":
                                    $prefix="IT";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "CSE":
                                    $prefix="CSE";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "ECE":
                                    $prefix="ECE";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "EEE":
                                    $prefix="EEE";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "EE":
                                    $prefix="EE";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "ME":
                                    $prefix="ME";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                case "CE":
                                    $prefix="CE";
                                    $rand=rand(9999999,1234567);
                                    $suffix=substr($user_email,0,3);
                                     $id_generated=$prefix.$rand.$suffix;
                                    break;
                                
                           }
                               ?>
                    <form method="POST">
                            <div class="form-group">
                    <label for="email">User Email: </label>
                    <input type="email" id="email" name="email" class="form-control" readonly value="<?php echo $user_email;?>"/>
                            </div>
                            <div class="form-group">
                    <label for="rollNo">User RollNo.</label>
                    <input type="text" id="rollNo" name="rollNo" class="form-control" readonly value="<?php echo $user_RollNo;?>"/>
                            <div class="form-group">
                    <label for="branch">User Branch</label>
                    <input type="text" id="branch" name="branch" class="form-control" readonly value="<?php echo $branch;?>"/>
                            </div>
                            <div class="form-group">
                    <label for="id_generated">ID generated by system</label>
                    <input type="text" id="id_generated" name="id_generated" class="form-control" readonly value="<?php echo strtoupper($id_generated);?>"/>
                            </div>
                            <div class="form-group">
                                <button type="submit" name="update"  class="form-control btn btn-success">Update user ID</button>
                            </div>
                    </form>
                           <?php
                           }
                           else 
                           {
                               echo "record not found";
                           }
                        ?>       
            </div>
            <div class="col-sm-6">
            </div>
        </div>    
</body>
</html>       
<?php 
if(isset($_POST['update']))
{
    $user_email=$_POST['email'];
    $id_generated=$_POST['id_generated'];
    $stmt="UPDATE user_db set id_generated='$id_generated' where email='$user_email'";
    $result=$conn->query($stmt);
    if($result)
    {
        $deleteStmt="DELETE  from idrequest where userEmail='$user_email'";
        $run=$conn->query($deleteStmt);
        if($run)
        {echo "<script>alert('Update successfully')</script>";
            echo "<script>window.location.href='id_request.php'</script>";
        }
        
    }
    else 
    echo "<script>alert('Something went wrong!')</script>";
}
?> 